import { getWorkspace } from '@schematics/angular/utility/workspace';
import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import type { IconifyJSON } from '@iconify/types';
import { GenerateIconSubsetOptions } from './schema';
import { buildSubset, iconSetJsonPath, readJsonFile, scanIcons } from './icons';
import { patchAppConfig } from '../utils';

/** Stable file header so reruns stay byte-identical. */
const OUTPUT_HEADER =
  '// Auto-generated by ngx-iconify-stack:generate-icon-subset — do not edit manually';
const TYPE_IMPORT = `import type { IconifyJSON } from '@iconify/types';`;

/** Both the empty and non-empty variants share this shape (type import included). */
function renderSubsetFile(collections: IconifyJSON[]): string {
  return (
    `${OUTPUT_HEADER}\n${TYPE_IMPORT}\n\n` +
    `export const iconSubset: IconifyJSON[] = ${JSON.stringify(collections, null, 2)};\n`
  );
}

/** Split a `a && b && c` script chain into trimmed segments. */
function splitChain(script: string): string[] {
  return script
    .split('&&')
    .map((seg) => seg.trim())
    .filter(Boolean);
}

/** True for legacy `collect-icons` segments or the new `npm run icons` marker. */
function isIconSegment(seg: string): boolean {
  return seg.includes('collect-icons') || seg === 'npm run icons';
}

/**
 * Idempotent script wiring (marker-based, so reruns never double-append):
 * adds the `icons` script, chains it into prebuild, strips it from prestart,
 * and removes the dead legacy `collect-icons` entry.
 */
function wirePackageScripts(
  pkg: { scripts: Record<string, string> },
  projectName: string,
): void {
  pkg.scripts ??= {};

  if (!(pkg.scripts['icons'] ?? '').includes('generate-icon-subset')) {
    pkg.scripts['icons'] = `ng generate ngx-iconify-stack:generate-icon-subset --project ${projectName}`;
  }

  const prebuildSegs = splitChain(pkg.scripts['prebuild'] ?? '');
  if (prebuildSegs.some(isIconSegment)) {
    pkg.scripts['prebuild'] = prebuildSegs
      .map((seg) => (isIconSegment(seg) ? 'npm run icons' : seg))
      .join(' && ');
  } else if (prebuildSegs.length > 0) {
    pkg.scripts['prebuild'] = `${prebuildSegs.join(' && ')} && npm run icons`;
  } else {
    pkg.scripts['prebuild'] = 'npm run icons';
  }

  const keptPrestart = splitChain(pkg.scripts['prestart'] ?? '').filter(
    (seg) => !isIconSegment(seg),
  );
  if (keptPrestart.length > 0) {
    pkg.scripts['prestart'] = keptPrestart.join(' && ');
  } else {
    delete pkg.scripts['prestart'];
  }

  delete pkg.scripts['collect-icons'];
}

export function generateIconSubset(options: GenerateIconSubsetOptions): Rule {
  return async (tree: Tree, context: SchematicContext) => {
    const workspace = await getWorkspace(tree);
    const projectName =
      options.project ??
      (workspace.extensions['defaultProject'] as string | undefined) ??
      [...workspace.projects.keys()][0];
    const project = workspace.projects.get(projectName);
    const sourceRoot = project?.sourceRoot ?? 'src';

    // ── 1. Inline scan + subset build (replaces the collect-icons script) ──
    const found = scanIcons(tree, sourceRoot);
    const collections = buildSubset(tree, found, context.logger);

    const outputPath = `${sourceRoot}/generated/icon-subset.ts`.replace(/^\//, '');
    const content = renderSubsetFile(collections);
    if (tree.exists(outputPath)) {
      tree.overwrite(outputPath, content);
    } else {
      tree.create(outputPath, content);
    }
    context.logger.info(`✓ Subset written to ${outputPath}`);

    // ── 2. Legacy migration + script wiring + missing-set auto-install ──
    const pkgPath = '/package.json';
    if (tree.exists(pkgPath)) {
      if (tree.exists('/scripts/collect-icons.mjs')) {
        tree.delete('/scripts/collect-icons.mjs');
        context.logger.info('✓ Deleted legacy scripts/collect-icons.mjs');
      }

      const pkg = JSON.parse(tree.read(pkgPath)!.toString()) as {
        scripts: Record<string, string>;
        dependencies?: Record<string, string>;
      };
      pkg.scripts ??= {};

      // Auto-install missing sets: add `@iconify-json/<prefix>` to ROOT dependencies
      // only when the set is not installed and not already listed (idempotent).
      // No NodePackageInstallTask — prebuild must never trigger npm install; the
      // developer's next npm install/ci resolves the new dependency.
      pkg.dependencies ??= {};
      for (const prefix of found.keys()) {
        const depName = `@iconify-json/${prefix}`;
        if (pkg.dependencies[depName]) continue;
        if (readJsonFile(tree, iconSetJsonPath(prefix)) !== null) continue;
        pkg.dependencies[depName] = '^1.0.0';
        context.logger.info(
          `✓ Added ${depName} to dependencies (next npm install resolves it)`,
        );
      }

      wirePackageScripts(pkg, projectName);
      tree.overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    }

    // ── 3. Wire the subset into app.config via the shared patcher ──
    await patchAppConfig(
      tree,
      context,
      sourceRoot,
      'provideIconify({ offlineCollections: iconSubset })',
      'provideIconify',
      'ngx-iconify-stack',
      projectName,
      [{ symbol: 'iconSubset', module: '../generated/icon-subset' }],
    );
  };
}
