import { describe, expect, it } from 'vitest';
import { fileURLToPath } from 'node:url';
import { HostTree, Tree } from '@angular-devkit/schematics';
import { SchematicTestRunner } from '@angular-devkit/schematics/testing';

/**
 * Compiled collection under test (produced by build:schematic). The dist tree is
 * one directory deeper than the collection smoke spec, hence the extra `../`.
 */
const COLLECTION_PATH = fileURLToPath(
  new URL('../../../../../dist/ngx-iconify-stack/schematics/collection.json', import.meta.url),
);

const OUTPUT_PATH = '/projects/docs/src/generated/icon-subset.ts';
const APP_CONFIG_PATH = '/projects/docs/src/app/app.config.ts';

/** Minimal workspace mirroring the real repo: docs project, sourceRoot under projects/. */
function createWorkspaceTree(withIcons = true): Tree {
  const tree = new HostTree();
  tree.create(
    '/angular.json',
    JSON.stringify(
      {
        version: 1,
        projects: {
          docs: {
            projectType: 'application',
            root: 'projects/docs',
            sourceRoot: 'projects/docs/src',
            prefix: 'app',
            architect: {},
          },
        },
      },
      null,
      2,
    ),
  );
  tree.create(
    '/package.json',
    JSON.stringify(
      {
        name: 'docs-workspace',
        version: '0.0.0',
        scripts: { prebuild: 'npm run ngx-theme-stack:sync' },
      },
      null,
      2,
    ),
  );
  tree.create(
    APP_CONFIG_PATH,
    [
      `import { ApplicationConfig } from '@angular/core';`,
      `import { provideIconify } from 'ngx-iconify-stack';`,
      ``,
      `export const appConfig: ApplicationConfig = {`,
      `  providers: [provideIconify()],`,
      `};`,
      ``,
    ].join('\n'),
  );
  // Mock installed icon set: readJsonFile reads the tree first, so the virtual
  // node_modules/@iconify-json/foo/icons.json stands in for the real package.
  tree.create(
    '/node_modules/@iconify-json/foo/icons.json',
    JSON.stringify({
      prefix: 'foo',
      icons: {
        home: { body: '<path d="home"/>' },
        star: { body: '<path d="star"/>' },
      },
    }),
  );
  if (withIcons) {
    tree.create(
      '/projects/docs/src/app/app.component.html',
      `<ngx-iconify icon="foo:home"></ngx-iconify>`,
    );
    tree.create(
      '/projects/docs/src/app/app.component.ts',
      `export class AppComponent { icon = 'foo:star'; }`,
    );
    // Decoy OUTSIDE the source root: a hardcoded `src` scan (the pre-fix bug)
    // would pick this up; getWorkspace-based resolution must not.
    tree.create('/src/decoy.ts', `const decoy = 'decoy:home';`);
  }
  return tree;
}

/** Extract the array literal written to the generated subset file. */
function parseSubset(content: string): unknown[] {
  const assignIdx = content.indexOf('= ['); // skip the type-annotation bracket in `iconSubset: IconifyJSON[]`
  const start = assignIdx + 2;
  const end = content.lastIndexOf(']');
  return JSON.parse(content.slice(start, end + 1)) as unknown[];
}

async function runFactory(tree: Tree): Promise<Tree> {
  const runner = new SchematicTestRunner('ngx-iconify-stack', COLLECTION_PATH);
  return runner.runSchematic('generate-icon-subset', { project: 'docs' }, tree);
}

describe('generate-icon-subset factory (inline execution)', () => {
  it('writes the subset inline to <sourceRoot>/generated/icon-subset.ts with no collect-icons script', async () => {
    const tree = await runFactory(createWorkspaceTree());

    expect(tree.exists('/scripts/collect-icons.mjs')).toBe(false);
    expect(tree.exists(OUTPUT_PATH)).toBe(true);

    const content = tree.readContent(OUTPUT_PATH);
    expect(content).toContain('// Auto-generated by ngx-iconify-stack:generate-icon-subset');
    expect(content).toContain("import type { IconifyJSON } from '@iconify/types';");
    expect(content).toContain('export const iconSubset: IconifyJSON[] = [');
  });

  it('produces the expected IconifyJSON[] shape with width/height defaults of 24', async () => {
    const tree = await runFactory(createWorkspaceTree());

    const collections = parseSubset(tree.readContent(OUTPUT_PATH));
    expect(collections).toEqual([
      {
        prefix: 'foo',
        icons: {
          home: { body: '<path d="home"/>' },
          star: { body: '<path d="star"/>' },
        },
        width: 24,
        height: 24,
      },
    ]);
  });

  it('resolves the source root via getWorkspace, ignoring files outside it', async () => {
    const tree = await runFactory(createWorkspaceTree());

    const content = tree.readContent(OUTPUT_PATH);
    expect(content).toContain('"prefix": "foo"');
    expect(content).not.toContain('decoy');
  });

  it('keeps wiring the offlineCollections provider into app.config.ts', async () => {
    const tree = await runFactory(createWorkspaceTree());

    const appConfig = tree.readContent(APP_CONFIG_PATH);
    expect(appConfig).toContain(`import { iconSubset } from '../generated/icon-subset';`);
    expect(appConfig).toContain('provideIconify({ offlineCollections: iconSubset })');
  });

  it('keeps chaining the prebuild hook (rewired to npm run icons in PR3)', async () => {
    const tree = await runFactory(createWorkspaceTree());

    const pkg = JSON.parse(tree.readContent('/package.json'));
    expect(pkg.scripts.prebuild).toBe(
      'npm run ngx-theme-stack:sync && node scripts/collect-icons.mjs',
    );
  });

  it('writes the empty subset with the IconifyJSON type import when no icons are found', async () => {
    const tree = await runFactory(createWorkspaceTree(false));

    expect(tree.exists(OUTPUT_PATH)).toBe(true);
    const content = tree.readContent(OUTPUT_PATH);
    expect(content).toContain("import type { IconifyJSON } from '@iconify/types';");
    expect(parseSubset(content)).toEqual([]);
    expect(content).toContain('export const iconSubset: IconifyJSON[] = [];');
  });

  it('is idempotent: rerunning produces a byte-identical subset with no duplicated wiring', async () => {
    const firstTree = await runFactory(createWorkspaceTree());
    const secondTree = await runFactory(firstTree);

    // Explicit guards first: a missing output file would silently read as ''.
    expect(firstTree.exists(OUTPUT_PATH)).toBe(true);
    expect(secondTree.exists(OUTPUT_PATH)).toBe(true);
    expect(secondTree.exists('/scripts/collect-icons.mjs')).toBe(false);

    expect(secondTree.readContent(OUTPUT_PATH)).toBe(firstTree.readContent(OUTPUT_PATH));
    expect(secondTree.readContent(APP_CONFIG_PATH)).toBe(firstTree.readContent(APP_CONFIG_PATH));
    expect(secondTree.readContent('/package.json')).toBe(firstTree.readContent('/package.json'));

    const appConfig = secondTree.readContent(APP_CONFIG_PATH);
    expect(appConfig.match(/offlineCollections/g)).toHaveLength(1);
    expect(appConfig.match(/\.\.\/generated\/icon-subset/g)).toHaveLength(1);
  });
});
