import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { spawnSync } from 'node:child_process';
import type { IconifyJSON } from '@iconify/types';
import { GenerateIconSubsetOptions } from './schema';
import {
  buildSubset,
  iconSetJsonPath,
  mergeManifestIcons,
  readJsonFile,
  scanIcons,
} from './icons';
import {
  detectPackageManager,
  detectRunner,
  patchAppConfig,
  resolveConfigFile,
  resolveProject,
  toRelativeImport,
  wireIconifyScripts,
} from '../utils';

/** Stable file header so reruns stay byte-identical. */
const OUTPUT_HEADER =
  '// Auto-generated by ngx-iconify-stack:generate-icon-subset — do not edit manually';
const TYPE_IMPORT = `import type { IconifyJSON } from '@iconify/types';`;

/** DevDependency range pinned for `@iconify-json/<prefix>` sets. */
const ICONIFY_JSON_VERSION = '^1.0.0';

/** Both the empty and non-empty variants share this shape (type import included). */
function renderSubsetFile(collections: IconifyJSON[]): string {
  return (
    `${OUTPUT_HEADER}\n${TYPE_IMPORT}\n\n` +
    `export const iconSubset: IconifyJSON[] = ${JSON.stringify(collections, null, 2)};\n`
  );
}

/** Package-manager subcommand that installs named packages (npm/pnpm install, yarn/bun add). */
export function directedInstallCommand(packageManager: string): string {
  return packageManager === 'yarn' || packageManager === 'bun' ? 'add' : 'install';
}

/**
 * Directed install of ONLY the missing `@iconify-json/<prefix>` sets, run
 * synchronously BEFORE the subset is built so the same run produces a complete
 * subset. Falls back gracefully (warning + partial subset) when the install
 * fails — e.g. CI with a frozen lockfile — instead of breaking the build.
 * Idempotent: a set already installed is never reinstalled.
 */
export function installMissingSets(
  missing: string[],
  packageManager: string,
  logger: { info(message: string): void; warn(message: string): void },
): void {
  const packages = missing.map((prefix) => `@iconify-json/${prefix}@${ICONIFY_JSON_VERSION}`);
  const command = directedInstallCommand(packageManager);
  logger.info(`Installing missing icon sets: ${packages.join(', ')}`);
  try {
    const result = spawnSync(packageManager, [command, ...packages], {
      cwd: process.cwd(),
      stdio: 'inherit',
    });
    if (result.status !== 0) {
      logger.warn(
        `Install of icon sets failed (exit ${result.status}) — subset will be partial ` +
          `until you run "${packageManager} ${command} ${packages.join(' ')}" and rebuild.`,
      );
    }
  } catch (err) {
    logger.warn(
      `Could not install icon sets (${String(err)}) — subset will be partial until the ` +
        `sets are installed and the subset is regenerated.`,
    );
  }
}

/**
 * Apply missing-set dependency declarations to an already-parsed package.json.
 * A set counts as missing only when it is neither installed nor already listed
 * in dependencies, so reruns never duplicate or reinstall (idempotent). Does
 * not persist — callers decide when to write so the file is written at most
 * once per run. Returns the missing prefixes so callers can schedule the
 * directed install.
 */
function declareMissingSetDeps(
  pkg: { dependencies?: Record<string, string> },
  tree: Tree,
  prefixes: Iterable<string>,
  logger: { info(message: string): void },
): string[] {
  pkg.dependencies ??= {};
  const missing: string[] = [];
  for (const prefix of prefixes) {
    const depName = `@iconify-json/${prefix}`;
    if (pkg.dependencies[depName]) continue;
    if (readJsonFile(tree, iconSetJsonPath(prefix)) !== null) continue;
    pkg.dependencies[depName] = ICONIFY_JSON_VERSION;
    missing.push(prefix);
    logger.info(`✓ Added ${depName} to dependencies`);
  }
  return missing;
}

/**
 * Declare + directed-install the missing `@iconify-json/<prefix>` sets for the
 * given prefixes. Reads package.json once, applies the declarations, persists
 * only when something changed, then runs the directed install. Shared by
 * generate-icon-subset and add-icon.
 */
export function declareAndInstallMissingSets(
  tree: Tree,
  context: SchematicContext,
  prefixes: Iterable<string>,
): void {
  const pkgPath = '/package.json';
  const packageManager = detectPackageManager(tree);
  const missing: string[] = [];
  if (tree.exists(pkgPath)) {
    const pkg = JSON.parse(tree.read(pkgPath)!.toString()) as {
      dependencies?: Record<string, string>;
    };
    missing.push(...declareMissingSetDeps(pkg, tree, prefixes, context.logger));
    if (missing.length > 0) {
      tree.overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    }
  }

  if (missing.length > 0) {
    installMissingSets(missing, packageManager, context.logger);
  }
}

/**
 * Full subset pipeline shared by generate-icon-subset and add-icon:
 * resolve project → scan templates → merge the dynamic-icon manifest →
 * declare/install missing sets → build + write icon-subset.ts → script wiring
 * and cleanup → wire `provideIconify` into the app config.
 */
export async function regenerateIconSubset(
  tree: Tree,
  context: SchematicContext,
  options: GenerateIconSubsetOptions,
): Promise<string> {
  const { projectName, sourceRoot } = await resolveProject(tree, options);

  // ── 1. Inline scan + merge dynamic icons from the manifest ──
  const found = scanIcons(tree, sourceRoot);
  const manifestRefs = mergeManifestIcons(tree, sourceRoot, found);
  if (manifestRefs.length > 0) {
    context.logger.info(
      `✓ Manifest: +${manifestRefs.length} dynamic icons (${manifestRefs.join(', ')})`,
    );
  }

  // ── 2/4. Declare missing deps + wire scripts against ONE package.json read,
  // install missing sets BEFORE building the subset, and persist only when
  // anything actually changed (never an unconditional rewrite). ──
  const pkgPath = '/package.json';
  let missing: string[] = [];
  let scriptsChanged = false;
  if (tree.exists(pkgPath)) {
    // One-shot cleanup from older library versions that shipped a root script.
    if (tree.exists('/scripts/collect-icons.mjs')) {
      tree.delete('/scripts/collect-icons.mjs');
      context.logger.info('✓ Deleted obsolete scripts/collect-icons.mjs');
    }

    const pkg = JSON.parse(tree.read(pkgPath)!.toString()) as {
      dependencies?: Record<string, string>;
      scripts?: Record<string, string>;
    };
    pkg.scripts ??= {};

    const packageManager = detectPackageManager(tree);
    missing = declareMissingSetDeps(pkg, tree, found.keys(), context.logger);
    if (missing.length > 0) {
      installMissingSets(missing, packageManager, context.logger);
    }

    scriptsChanged = wireIconifyScripts(pkg, projectName, packageManager, detectRunner(tree));

    if (missing.length > 0 || scriptsChanged) {
      tree.overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    }
  }

  // ── 3. Build + write the subset (sets are now installed) ──
  const collections = buildSubset(tree, found, context.logger);

  const outputPath = `${sourceRoot}/ngx-iconify/icon-subset.ts`.replace(/^\//, '');
  const content = renderSubsetFile(collections);
  if (tree.exists(outputPath)) {
    tree.overwrite(outputPath, content);
  } else {
    tree.create(outputPath, content);
  }
  context.logger.info(`✓ Subset written to ${outputPath}`);

  // ── 5. Wire the subset into app.config via the shared patcher ──
  const configFile = resolveConfigFile(tree, sourceRoot) ?? `${sourceRoot}/app/app.config.ts`;
  const subsetImport = toRelativeImport(configFile, outputPath);

  await patchAppConfig(
    tree,
    context,
    sourceRoot,
    'provideIconify({ offlineCollections: iconSubset })',
    'provideIconify',
    'ngx-iconify-stack',
    projectName,
    [{ symbol: 'iconSubset', module: subsetImport }],
  );

  return projectName;
}

export function generateIconSubset(options: GenerateIconSubsetOptions): Rule {
  return async (tree: Tree, context: SchematicContext) => {
    await regenerateIconSubset(tree, context, options);
  };
}
