import { getWorkspace } from '@schematics/angular/utility/workspace';
import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import type { IconifyJSON } from '@iconify/types';
import { GenerateIconSubsetOptions } from './schema';
import { buildSubset, iconSetJsonPath, readJsonFile, scanIcons } from './icons';
import {
  assertAngularProject,
  detectPackageManager,
  patchAppConfig,
  resolveProjectName,
  toRelativeImport,
  wireIconifyScripts,
} from '../utils';

/** Stable file header so reruns stay byte-identical. */
const OUTPUT_HEADER =
  '// Auto-generated by ngx-iconify-stack:generate-icon-subset — do not edit manually';
const TYPE_IMPORT = `import type { IconifyJSON } from '@iconify/types';`;

/** Both the empty and non-empty variants share this shape (type import included). */
function renderSubsetFile(collections: IconifyJSON[]): string {
  return (
    `${OUTPUT_HEADER}\n${TYPE_IMPORT}\n\n` +
    `export const iconSubset: IconifyJSON[] = ${JSON.stringify(collections, null, 2)};\n`
  );
}

/** Config entry point used when wiring the subset import (Angular 20+ standalone). */
function resolveConfigFile(tree: Tree, sourceRoot: string): string {
  const appConfigPath = `${sourceRoot}/app/app.config.ts`.replace(/^\//, '');
  const mainPath = `${sourceRoot}/main.ts`.replace(/^\//, '');
  if (tree.exists(appConfigPath)) return appConfigPath;
  if (tree.exists(mainPath)) return mainPath;
  return appConfigPath;
}

export function generateIconSubset(options: GenerateIconSubsetOptions): Rule {
  return async (tree: Tree, context: SchematicContext) => {
    const projectName = await resolveProjectName(tree, options);
    const workspace = await getWorkspace(tree);
    const project = workspace.projects.get(projectName);
    const sourceRoot = project?.sourceRoot ?? 'src';

    assertAngularProject(tree, sourceRoot, projectName);

    // ── 1. Inline scan + subset build ──
    const found = scanIcons(tree, sourceRoot);
    const collections = buildSubset(tree, found, context.logger);

    const outputPath = `${sourceRoot}/ngx-iconify/icon-subset.ts`.replace(/^\//, '');
    const content = renderSubsetFile(collections);
    if (tree.exists(outputPath)) {
      tree.overwrite(outputPath, content);
    } else {
      tree.create(outputPath, content);
    }
    context.logger.info(`✓ Subset written to ${outputPath}`);

    // ── 2. Script wiring + missing-set auto-install ──
    const pkgPath = '/package.json';
    if (tree.exists(pkgPath)) {
      // One-shot cleanup from older library versions that shipped a root script.
      if (tree.exists('/scripts/collect-icons.mjs')) {
        tree.delete('/scripts/collect-icons.mjs');
        context.logger.info('✓ Deleted obsolete scripts/collect-icons.mjs');
      }

      const pkg = JSON.parse(tree.read(pkgPath)!.toString()) as {
        scripts: Record<string, string>;
        dependencies?: Record<string, string>;
      };
      pkg.scripts ??= {};

      // Auto-install missing sets: add `@iconify-json/<prefix>` to ROOT dependencies
      // only when the set is not installed and not already listed (idempotent).
      // No NodePackageInstallTask — prebuild must never trigger npm install; the
      // developer's next npm install/ci resolves the new dependency.
      pkg.dependencies ??= {};
      for (const prefix of found.keys()) {
        const depName = `@iconify-json/${prefix}`;
        if (pkg.dependencies[depName]) continue;
        if (readJsonFile(tree, iconSetJsonPath(prefix)) !== null) continue;
        pkg.dependencies[depName] = '^1.0.0';
        context.logger.info(
          `✓ Added ${depName} to dependencies (next npm install resolves it)`,
        );
      }

      wireIconifyScripts(pkg, projectName, detectPackageManager(tree));
      tree.overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    }

    // ── 3. Wire the subset into app.config via the shared patcher ──
    const configFile = resolveConfigFile(tree, sourceRoot);
    const subsetImport = toRelativeImport(configFile, outputPath);

    await patchAppConfig(
      tree,
      context,
      sourceRoot,
      'provideIconify({ offlineCollections: iconSubset })',
      'provideIconify',
      'ngx-iconify-stack',
      projectName,
      [{ symbol: 'iconSubset', module: subsetImport }],
    );
  };
}
