import { ChangeDetectionStrategy, Component } from '@angular/core';
import { NgxIconify } from 'ngx-iconify-stack';

interface TocItem {
  id: string;
  label: string;
}

interface ProviderOption {
  name: string;
  type: string;
  description: string;
}

interface ComponentInput {
  name: string;
  type: string;
  default: string;
  description: string;
}

interface Schematic {
  name: string;
  command: string;
  purpose: string;
}

interface CatalogTool {
  name: string;
  icon: string;
  description: string;
  command: string;
}

@Component({
  selector: 'docs-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgxIconify],
  templateUrl: './docs-page.component.html',
  styles: ``,
})
export class DocsPageComponent {
  readonly installCommand = 'ng add ngx-iconify-stack';

  readonly providerConfigCode = `import { provideIconify } from 'ngx-iconify-stack';
import { iconSubset } from '../ngx-iconify/icon-subset';

export const appConfig: ApplicationConfig = {
  providers: [
    provideIconify({ offlineCollections: iconSubset }),
  ],
};`;

  readonly componentExampleCode = `import { Component } from '@angular/core';
import { NgxIconify } from 'ngx-iconify-stack';

@Component({
  selector: 'app-example',
  standalone: true,
  imports: [NgxIconify],
  template: \`
    <ngx-iconify icon="mdi:home" [size]="24" />
    <ngx-iconify icon="lucide:arrow-right" color="#f59e0b" />
    <ngx-iconify icon="tabler:brand-github" inline />
  \`,
})
export class ExampleComponent {}`;

  readonly dynamicManifestCode = `export const dynamicSubsetIcons = ['mdi:home', 'mdi:user'] as const;`;

  readonly regenerateCode = `npm run ngx-iconify-stack:generate-icons

# or directly:
ng g ngx-iconify-stack:generate-icon-subset --project <name>

# Nx workspaces:
nx g ngx-iconify-stack:generate-icon-subset --project <name>`;

  readonly addIconCommand = 'ng g ngx-iconify-stack:add-icon --icon <prefix>:<name>';

  readonly toc: TocItem[] = [
    { id: 'getting-started', label: 'Getting started' },
    { id: 'provider', label: 'Provider configuration' },
    { id: 'component', label: 'Component usage' },
    { id: 'rendering', label: 'Rendering modes' },
    { id: 'schematics', label: 'Offline subset & schematics' },
    { id: 'tools', label: 'Catalog & validation tools' },
  ];

  readonly providerOptions: ProviderOption[] = [
    {
      name: 'offlineCollections',
      type: 'IconifyJSON[]',
      description: 'Icon sets rendered as SSR-safe inline SVG. Generated by the subset schematic.',
    },
    {
      name: 'apiProvider',
      type: '{ name: string; resource: string }',
      description: 'Optional custom Iconify API provider for the CDN fallback.',
    },
  ];

  readonly inputs: ComponentInput[] = [
    {
      name: 'icon',
      type: 'string',
      default: 'required',
      description: 'Iconify icon name, e.g. "mdi:home"',
    },
    {
      name: 'size',
      type: 'number | string',
      default: '16px',
      description: 'Sets both width and height (e.g. "1em", "24px", 24)',
    },
    {
      name: 'width',
      type: 'number | string',
      default: '16px',
      description: 'Explicit width (overrides size)',
    },
    {
      name: 'height',
      type: 'number | string',
      default: "icon's native",
      description:
        "Explicit height (overrides size); falls back to the icon's native height when unset",
    },
    {
      name: 'color',
      type: 'string',
      default: '—',
      description: 'CSS color for the icon',
    },
    {
      name: 'class',
      type: 'string',
      default: '—',
      description: 'CSS class added to the rendered icon element',
    },
    {
      name: 'inline',
      type: 'boolean',
      default: 'false',
      description: 'Align to text baseline (boolean attribute); applied on the host element',
    },
    {
      name: 'forceCdn',
      type: 'boolean',
      default: 'false',
      description: 'Force CDN resolution and EXCLUDE from the generated subset (boolean attribute)',
    },
    {
      name: 'mode',
      type: '"svg" | "bg" | "mask" | "style"',
      default: '—',
      description: 'Rendering mode for <iconify-icon>',
    },
    {
      name: 'noObserver',
      type: 'boolean',
      default: 'false',
      description: 'Disable lazy loading observer (boolean attribute)',
    },
  ];

  readonly schematics: Schematic[] = [
    {
      name: 'generate-icon-subset',
      command: 'ng g ngx-iconify-stack:generate-icon-subset --project <name>',
      purpose:
        'Scans templates for icon="prefix:name" literals, merges the dynamic-icon manifest, builds src/ngx-iconify/icon-subset.ts, declares + installs missing @iconify-json/* sets, wires prebuild, and patches the provider.',
    },
    {
      name: 'add-icon',
      command: 'ng g ngx-iconify-stack:add-icon --project <name> --icon mdi:home (repeatable)',
      purpose:
        'Validates prefix:name, installs the set if missing, appends the icon to src/ngx-iconify/icon-manifest.ts (idempotent), and regenerates the subset through the same pipeline.',
    },
    {
      name: 'skill',
      command: 'ng g ngx-iconify-stack:skill --project <name>',
      purpose:
        'Regenerates the AI agent skill under .agents/skills/ngx-iconify-stack and declares the @iconify/collections devDependency for the read-only catalog tools.',
    },
    {
      name: 'list-sets',
      command:
        'ng g ngx-iconify-stack:list-sets --project <name> [--search <term>] [--category <name>] [--limit <N>]',
      purpose:
        'Lists real Iconify sets from the catalog (read-only, never installs). Use BEFORE choosing a set so you never invent one.',
    },
    {
      name: 'validate-set',
      command: 'ng g ngx-iconify-stack:validate-set --project <name> --prefix <prefix>',
      purpose:
        'Confirms a set exists in the catalog and prints its metadata + samples (read-only).',
    },
    {
      name: 'validate-icon',
      command:
        'ng g ngx-iconify-stack:validate-icon --project <name> --icon <prefix>:<name> (repeatable)',
      purpose:
        'Validates that an icon reference is well-formed AND the set/icon actually exist (read-only); fails hard on unknown sets/icons.',
    },
  ];

  readonly catalogTools: CatalogTool[] = [
    {
      name: 'list-sets',
      icon: 'mdi:tag-outline',
      description:
        'List real Iconify sets from the catalog — use it BEFORE choosing a set so you never invent one.',
      command:
        'ng g ngx-iconify-stack:list-sets --project <name> [--search <term>] [--category <name>] [--limit <N>]',
    },
    {
      name: 'validate-set',
      icon: 'mdi:server',
      description: 'Confirm a set exists in the catalog and print its metadata + samples.',
      command: 'ng g ngx-iconify-stack:validate-set --project <name> --prefix <prefix>',
    },
    {
      name: 'validate-icon',
      icon: 'mdi:check-circle',
      description:
        'Confirm an icon reference is well-formed AND the set/icon actually exist; fails hard on unknown sets/icons. Never hallucinate an icon name.',
      command: 'ng g ngx-iconify-stack:validate-icon --project <name> --icon <prefix>:<name>',
    },
  ];
}
