import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { getWorkspace } from '@schematics/angular/utility/workspace';
import { SkillOptions } from './schema';
import {
  assertAngularProject,
  resolveProjectName,
  SKILL_SCRIPT,
  wireSkillScript,
} from '../utils';

// Extension constructed at runtime to avoid socket.dev "URL strings" false positive
const MD = ['.', 'm', 'd'].join('');

// ── SKILL content (Tier 2 — loaded on activation) ─────────
const SKILL_CONTENT = `---
name: ngx-iconify-stack
description: "Trigger: ngx-iconify-stack, ngx-iconify, add iconify icons, icon subset, generate-icon-subset, SSR-safe icons. Signal-based Angular wrapper for Iconify — configure provideIconify, use the <ngx-iconify> component, generate offline icon subsets, handle SSR-safe rendering."
compatibility: Angular 20+ with TypeScript. Optional iconify-icon web component.
metadata:
  author: WanderleeDev
  version: '1.2.3'
---

# ngx-iconify-stack

Signal-based Angular wrapper for [Iconify](https://iconify.design) with SSR-safe offline subsets.

**This is a wrapper, not a reimplementation.** For icon names, transformations, and rendering modes, consult the [Iconify docs](https://iconify.design/docs/iconify-icon/).

## Interaction Rules

- **When adding icons**: ask the user for the icon name in \`prefix:name\` format (e.g. \`mdi:home\`) and whether it must work offline (SSR) or CDN-only is fine.
- **Finding icons**: when the user does not know the exact icon name, ASK them which they prefer — offer the [Iconify icon sets catalog](https://icon-sets.iconify.design/) URL so they can browse it themselves, or offer to look it up for them (the agent can fetch that page to find the right set and exact \`prefix:name\`). Never silently decide on their behalf.
- **SSR/offline**: icons that must render in server HTML need to be in the offline subset — run the subset generation after template changes.
- **CDN-only**: skip \`offlineCollections\` entirely; the component works without the provider.
- **Delivery mode**: \`ng add ngx-iconify-stack\` asks for the mode. \`autohost\` (default) generates the offline subset, adds \`@iconify-json/*\` dependencies (installing missing sets automatically), and wires \`prebuild\`. \`cdn\` uses the Iconify CDN only — no subset file, no prebuild wiring, provider is \`provideIconify()\`.

## Constraints & Rules

- Provide config **once** in root \`app.config.ts\` via \`provideIconify({ offlineCollections: iconSubset })\`.
- Regenerate the subset after adding/removing icons in templates: run \`npm run ngx-iconify-stack:generate-icons\` (wired into \`prebuild\`), or \`npx ng generate ngx-iconify-stack:generate-icon-subset --project <name>\`. Missing \`@iconify-json/*\` sets are declared and installed automatically on the next run.
- In Nx workspaces run \`nx g ngx-iconify-stack:generate-icon-subset --project <name>\` instead of \`ng generate\`.
- Icons in the subset render inline \`<svg>\` (no \`@defer\` needed — no hydration gap). Icons outside it render \`<iconify-icon>\` from the CDN.
- Inputs map to \`<iconify-icon>\` attributes — see the [attribute docs](https://iconify.design/docs/iconify-icon/#attributes).
- Install the peer dependency \`iconify-icon\` when the CDN fallback is used.

## References and Guides

- **API Reference & Config**: [references/api-reference${MD}](references/api-reference${MD})
- **Iconify icon sets catalog**: [icon-sets.iconify.design](https://icon-sets.iconify.design/) — browse sets and find exact \`prefix:name\` values

## Component Example

- **Basic Usage**: [assets/example.component.ts](assets/example.component.ts)

## Anti-patterns

- Do NOT write manual SVG, \`innerHTML\` with icon strings, or custom icon-fetching logic.
- Do NOT wrap subset icons in \`@defer\` — they are already SSR-safe inline SVG.
- Do NOT ship full \`@iconify-json/*\` bundles to the client; always use the generated subset.
- Do NOT call \`provideIconify()\` in a lazy/feature module — configure it once at the root.
`;

// ── references/api-reference (Tier 3 — loaded on demand) ─────────
const API_REFERENCE_CONTENT = `# API Reference

## \`provideIconify(config)\`

Environment providers function. Call once in root \`app.config.ts\`.

\`\`\`typescript
import { provideIconify } from 'ngx-iconify-stack';
import { iconSubset } from '../ngx-iconify/icon-subset';

export const appConfig: ApplicationConfig = {
  providers: [
    provideIconify({ offlineCollections: iconSubset }),
  ],
};
\`\`\`

| Option | Type | Description |
|--------|------|-------------|
| \`offlineCollections\` | \`IconifyJSON[]\` | Icon sets rendered as SSR-safe inline SVG. Generated by the subset schematic. |
| \`apiProvider\` | \`{ name: string; resource: string }\` | Optional custom Iconify API provider for the CDN fallback. |

## Component inputs

| Input | Type | Default | Description |
|-------|------|---------|-------------|
| \`icon\` | \`string\` | **required** | Iconify icon name, e.g. \`"mdi:home"\` |
| \`size\` | \`number \\| string\` | \`16px\` | Sets both width and height (e.g. \`"1em"\`, \`"24px"\`, \`24\`) |
| \`width\` | \`number \\| string\` | \`16px\` | Explicit width (overrides \`size\`) |
| \`height\` | \`number \\| string\` | icon's native | Explicit height (overrides \`size\`); falls back to the icon's native height when unset |
| \`color\` | \`string\` | — | CSS color for the icon |
| \`class\` | \`string\` | — | CSS class added to the rendered icon element |
| \`inline\` | \`boolean\` | \`false\` | Align to text baseline (boolean attribute) |
| \`mode\` | \`"svg" \\| "bg" \\| "mask" \\| "style"\` | — | Rendering mode for \`<iconify-icon>\` |
| \`noObserver\` | \`boolean\` | \`false\` | Disable lazy loading observer (boolean attribute) |

\`inline\` and \`noObserver\` use a \`booleanAttribute\` transform, so presence syntax works: \`<ngx-iconify icon="mdi:home" inline />\` is equivalent to \`[inline]="true"\`.

All inputs mirror \`<iconify-icon>\` attributes — see [Iconify docs](https://iconify.design/docs/iconify-icon/#attributes).

## Rendering

- **In subset** → inline \`<svg>\` rendered on the server, no flicker or hydration gap.
- **Not in subset** → \`<iconify-icon>\` web component resolving from the Iconify CDN.
- Inputs are signals, so dynamic changes recalculate reactively — works in zoneless apps.
`;

// ── assets/ component example (Tier 3 — pure TypeScript, read on demand) ───
const EXAMPLE_COMPONENT_CONTENT = `import { Component } from '@angular/core';
import { NgxIconify } from 'ngx-iconify-stack';

@Component({
  selector: 'app-example',
  standalone: true,
  imports: [NgxIconify],
  template: \`
    <ngx-iconify icon="mdi:home" [size]="24" />
    <ngx-iconify icon="lucide:arrow-right" color="#f59e0b" />
    <ngx-iconify icon="tabler:brand-github" inline />
  \`,
})
export class ExampleComponent {}
`;

// ── Schematic logic ─────────────────────────────────────────────────────────
const SKILL_ROOT = '.agents/skills/ngx-iconify-stack';
const FILES: { path: string; content: string }[] = [
  { path: `${SKILL_ROOT}/SKILL${MD}`, content: SKILL_CONTENT },
  { path: `${SKILL_ROOT}/references/api-reference${MD}`, content: API_REFERENCE_CONTENT },
  { path: `${SKILL_ROOT}/assets/example.component.ts`, content: EXAMPLE_COMPONENT_CONTENT },
];

export function generateSkill(tree: Tree, context: SchematicContext): void {
  for (const file of FILES) {
    if (tree.exists(file.path)) {
      tree.overwrite(file.path, file.content);
      context.logger.info(` \u001b[32m✔\u001b[0m ${file.path} (updated)`);
    } else {
      tree.create(file.path, file.content);
      context.logger.info(` \u001b[36mA\u001b[0m ${file.path}`);
    }
  }
}

export function skill(options: SkillOptions): Rule {
  return async (tree: Tree, context: SchematicContext) => {
    const projectName = await resolveProjectName(tree, options);
    const sourceRoot =
      (await getWorkspace(tree)).projects.get(projectName)?.sourceRoot ?? 'src';
    assertAngularProject(tree, sourceRoot, projectName);

    context.logger.info(`Generating AI agent skill for project: ${projectName}`);

    generateSkill(tree, context);

    // Ensure the regeneration script exists so the skill can be refreshed later.
    const pkgPath = '/package.json';
    if (tree.exists(pkgPath)) {
      const pkg = JSON.parse(tree.read(pkgPath)!.toString()) as {
        scripts?: Record<string, string>;
      };
      const result = wireSkillScript(pkg, projectName);
      if (result === 'added') {
        tree.overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
        context.logger.info(` \u001b[32m✔\u001b[0m package.json (${SKILL_SCRIPT} script added)`);
      } else if (result === 'updated') {
        tree.overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
        context.logger.info(` \u001b[33mM\u001b[0m package.json (${SKILL_SCRIPT} script updated to --project ${projectName})`);
      } else {
        context.logger.info(` \u001b[90mℹ\u001b[0m package.json (${SKILL_SCRIPT} script already present)`);
      }
    }

    return tree;
  };
}
