import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { SkillOptions } from './schema';

// Extension constructed at runtime to avoid socket.dev "URL strings" false positive
const MD = ['.', 'm', 'd'].join('');

// ── SKILL content (Tier 2 — loaded on activation) ─────────
const SKILL_CONTENT = `---
name: ngx-iconify-stack
description: "Trigger: ngx-iconify-stack, ngx-iconify, add iconify icons, icon subset, generate-icon-subset, SSR-safe icons. Signal-based Angular wrapper for Iconify — configure provideIconify, use the <ngx-iconify> component, generate offline icon subsets, handle SSR-safe rendering."
compatibility: Angular 20+ with TypeScript. Optional iconify-icon web component.
metadata:
  author: WanderleeDev
  version: '1.0.0'
---

# ngx-iconify-stack

Signal-based Angular wrapper for [Iconify](https://iconify.design) with SSR-safe offline subsets.

**This is a wrapper, not a reimplementation.** For icon names, transformations, and rendering modes, consult the [Iconify docs](https://iconify.design/docs/iconify-icon/).

## Interaction Rules

- **When adding icons**: ask the user for the icon name in \`prefix:name\` format (e.g. \`mdi:home\`) and whether it must work offline (SSR) or CDN-only is fine.
- **SSR/offline**: icons that must render in server HTML need to be in the offline subset — run the subset generation after template changes.
- **CDN-only**: skip \`offlineCollections\` entirely; the component works without the provider.

## Constraints & Rules

- Provide config **once** in root \`app.config.ts\` via \`provideIconify({ offlineCollections: iconSubset })\`.
- Regenerate the subset after adding/removing icons in templates: run \`npm run ngx-iconify-stack:generate-icons\` (wired into \`prebuild\`), or \`npx ng generate ngx-iconify-stack:generate-icon-subset --project <name>\`.
- Icons in the subset render inline \`<svg>\` (no \`@defer\` needed — no hydration gap). Icons outside it render \`<iconify-icon>\` from the CDN.
- Inputs map to \`<iconify-icon>\` attributes — see the [attribute docs](https://iconify.design/docs/iconify-icon/#attributes).
- Install the peer dependency \`iconify-icon\` when the CDN fallback is used.

## References and Guides

- **API Reference & Config**: [references/api-reference${MD}](references/api-reference${MD})

## Component Example

- **Basic Usage**: [assets/example.component.ts](assets/example.component.ts)

## Anti-patterns

- Do NOT write manual SVG, \`innerHTML\` with icon strings, or custom icon-fetching logic.
- Do NOT wrap subset icons in \`@defer\` — they are already SSR-safe inline SVG.
- Do NOT ship full \`@iconify-json/*\` bundles to the client; always use the generated subset.
- Do NOT call \`provideIconify()\` in a lazy/feature module — configure it once at the root.
`;

// ── references/api-reference (Tier 3 — loaded on demand) ─────────
const API_REFERENCE_CONTENT = `# API Reference

## \`provideIconify(config)\`

Environment providers function. Call once in root \`app.config.ts\`.

\`\`\`typescript
import { provideIconify } from 'ngx-iconify-stack';
import { iconSubset } from './generated/icon-subset';

export const appConfig: ApplicationConfig = {
  providers: [
    provideIconify({ offlineCollections: iconSubset }),
  ],
};
\`\`\`

| Option | Type | Description |
|--------|------|-------------|
| \`offlineCollections\` | \`IconifyJSON[]\` | Icon sets rendered as SSR-safe inline SVG. Generated by the subset schematic. |
| \`apiProvider\` | \`{ name: string; resource: string }\` | Optional custom Iconify API provider for the CDN fallback. |

## Component inputs

| Input | Type | Default | Description |
|-------|------|---------|-------------|
| \`icon\` | \`string\` | **required** | Iconify icon name, e.g. \`"mdi:home"\` |
| \`size\` | \`number\` | — | Sets both width and height |
| \`width\` | \`number \\| string\` | — | Explicit width (overrides \`size\`) |
| \`height\` | \`number \\| string\` | — | Explicit height (overrides \`size\`) |
| \`color\` | \`string\` | — | CSS color for the icon |
| \`class\` | \`string\` | — | CSS class added to the rendered icon element |
| \`inline\` | \`boolean\` | \`false\` | Align to text baseline |
| \`mode\` | \`"svg" \\| "bg" \\| "mask" \\| "style"\` | — | Rendering mode for \`<iconify-icon>\` |
| \`noObserver\` | \`boolean\` | \`false\` | Disable lazy loading observer |

All inputs mirror \`<iconify-icon>\` attributes — see [Iconify docs](https://iconify.design/docs/iconify-icon/#attributes).

## Rendering

- **In subset** → inline \`<svg>\` rendered on the server, no flicker or hydration gap.
- **Not in subset** → \`<iconify-icon>\` web component resolving from the Iconify CDN.
- Inputs are signals, so dynamic changes recalculate reactively — works in zoneless apps.
`;

// ── assets/ component example (Tier 3 — pure TypeScript, read on demand) ───
const EXAMPLE_COMPONENT_CONTENT = `import { Component } from '@angular/core';
import { NgxIconify } from 'ngx-iconify-stack';

@Component({
  selector: 'app-example',
  standalone: true,
  imports: [NgxIconify],
  template: \`
    <ngx-iconify icon="mdi:home" [size]="24" />
    <ngx-iconify icon="lucide:arrow-right" color="#f59e0b" />
    <ngx-iconify icon="tabler:brand-github" [inline]="true" />
  \`,
})
export class ExampleComponent {}
`;

// ── Schematic logic ─────────────────────────────────────────────────────────
const SKILL_ROOT = '.agents/skills/ngx-iconify-stack';
const FILES: { path: string; content: string }[] = [
  { path: `${SKILL_ROOT}/SKILL${MD}`, content: SKILL_CONTENT },
  { path: `${SKILL_ROOT}/references/api-reference${MD}`, content: API_REFERENCE_CONTENT },
  { path: `${SKILL_ROOT}/assets/example.component.ts`, content: EXAMPLE_COMPONENT_CONTENT },
];

export function generateSkill(tree: Tree, context: SchematicContext): void {
  for (const file of FILES) {
    if (tree.exists(file.path)) {
      tree.overwrite(file.path, file.content);
      context.logger.info(` \u001b[32m✔\u001b[0m ${file.path} (updated)`);
    } else {
      tree.create(file.path, file.content);
      context.logger.info(` \u001b[36mA\u001b[0m ${file.path}`);
    }
  }
}

export function skill(options: SkillOptions): Rule {
  return (tree: Tree, context: SchematicContext) => {
    context.logger.info(`Generating AI agent skill for project: ${options.project}`);
    generateSkill(tree, context);
    return tree;
  };
}
