import { ChangeDetectionStrategy, Component } from '@angular/core';
import { NgxIconify } from 'ngx-iconify-stack';

interface ProviderOption {
  name: string;
  type: string;
  description: string;
}

@Component({
  selector: 'docs-provider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgxIconify],
  templateUrl: './provider.component.html',
})
export class ProviderComponent {
  readonly providerConfigCode = `import { provideIconify } from 'ngx-iconify-stack';
import { iconSubset } from '../ngx-iconify/icon-subset';

export const appConfig: ApplicationConfig = {
  providers: [
    provideIconify({ offlineCollections: iconSubset }),
  ],
};`;

  readonly providerOptions: ProviderOption[] = [
    {
      name: 'offlineCollections',
      type: 'IconifyJSON[]',
      description: 'Icon sets rendered as SSR-safe inline SVG. Generated by the subset schematic.',
    },
    {
      name: 'apiProvider',
      type: '{ name: string; resource: string }',
      description: 'Optional custom Iconify API provider for the CDN fallback.',
    },
  ];
}
