import { describe, expect, it } from 'vitest';
import { fileURLToPath } from 'node:url';
import { HostTree, Tree } from '@angular-devkit/schematics';
import { SchematicTestRunner } from '@angular-devkit/schematics/testing';

/**
 * Compiled collection under test. This is the artifact produced by the
 * build:schematic pipeline: tsc (CJS) + build-schematics.mjs (JSON copies).
 */
const COLLECTION_PATH = fileURLToPath(
  new URL('../../../../dist/ngx-iconify-stack/schematics/collection.json', import.meta.url),
);

/** Minimal virtual workspace: angular.json with a `docs` project + root package.json. */
function createWorkspaceTree(): Tree {
  const tree = new HostTree();
  tree.create(
    '/angular.json',
    JSON.stringify(
      {
        version: 1,
        projects: {
          docs: {
            projectType: 'application',
            root: '',
            sourceRoot: 'src',
            prefix: 'app',
            architect: {},
          },
        },
      },
      null,
      2,
    ),
  );
  tree.create(
    '/package.json',
    JSON.stringify({ name: 'docs-workspace', version: '0.0.0', scripts: {} }, null, 2),
  );
  return tree;
}

describe('compiled schematics collection (dist)', () => {
  it('loads the collection and runs the ng-add factory, adding the iconify-icon dependency', async () => {
    const runner = new SchematicTestRunner('ngx-iconify-stack', COLLECTION_PATH);
    const tree = await runner.runSchematic('ng-add', { project: 'docs' }, createWorkspaceTree());

    const pkg = JSON.parse(tree.readContent('/package.json'));
    expect(pkg.dependencies['iconify-icon']).toBe('^3.0.2');
  });

  it('runs the generate-icon-subset factory, writing an inline subset (no collect-icons script)', async () => {
    const runner = new SchematicTestRunner('ngx-iconify-stack', COLLECTION_PATH);
    const tree = await runner.runSchematic(
      'generate-icon-subset',
      { project: 'docs' },
      createWorkspaceTree(),
    );

    expect(tree.exists('/scripts/collect-icons.mjs')).toBe(false);

    const output = tree.readContent('/src/generated/icon-subset.ts');
    expect(output).toContain('// Auto-generated by ngx-iconify-stack:generate-icon-subset');
    expect(output).toContain("import type { IconifyJSON } from '@iconify/types';");
    expect(output).toContain('export const iconSubset: IconifyJSON[] = [];');

    // prebuild is wired to the new `icons` script (no legacy collect-icons).
    const pkg = JSON.parse(tree.readContent('/package.json'));
    expect(pkg.scripts.prebuild).toContain('npm run icons');
    expect(pkg.scripts['collect-icons']).toBeUndefined();
  });
});
