// scripts/collect-icons.mjs — generated by ngx-iconify-stack
// Scans templates for <ngx-icon icon="set:name"> and builds an offline subset.
// Runs in prebuild so the subset stays in sync with actual icon usage.
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SRC = resolve(ROOT, 'projects', 'docs', 'src');
const OUT_FILE = resolve(SRC, 'generated', 'icon-subset.ts');

// ── scan: extract all "prefix:name" references from source files ──
function scanIcons(dir) {
  // Matches HTML: icon="mdi:home", icons="mdi:home"
  // Matches TS:   icon: 'mdi:home', icon: "mdi:home", icon = 'mdi:home'
  const pattern = /(?:icon|icons)\s*[:=]\s*["']([\w-]+:[\w-]+)["']/g;
  const found = new Map(); // prefix → Set<name>

  function walk(path) {
    let entries;
    try { entries = readdirSync(path, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const full = resolve(path, entry.name);
      if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
        walk(full);
      } else if (entry.isFile() && /\.(html|ts)$/.test(entry.name)) {
        const content = readFileSync(full, 'utf8');
        let match;
        while ((match = pattern.exec(content)) !== null) {
          const [_, ref] = match;
          const sep = ref.indexOf(':');
          if (sep === -1) continue;
          const prefix = ref.slice(0, sep);
          const name = ref.slice(sep + 1);
          if (!found.has(prefix)) found.set(prefix, new Set());
          found.get(prefix).add(name);
        }
      }
    }
  }

  walk(dir);
  return found;
}

// ── subset: build IconifyJSON with only the used icons ──
function buildSubset(found) {
  const collections = [];

  for (const [prefix, names] of found) {
    const pkgPath = resolve(ROOT, `node_modules/@iconify-json/${prefix}/icons.json`);
    if (!existsSync(pkgPath)) {
      console.warn(`  ⚠ Set "${prefix}" not found — install @iconify-json/${prefix}`);
      continue;
    }

    const fullSet = JSON.parse(readFileSync(pkgPath, 'utf8'));
    const subset = {
      prefix,
      icons: {},
      width: fullSet.width ?? 24,
      height: fullSet.height ?? 24,
    };

    let count = 0;
    for (const name of names) {
      if (fullSet.icons[name]) {
        subset.icons[name] = fullSet.icons[name];
        count++;
      } else {
        // Try alias chain
        let resolved = name;
        let depth = 0;
        while (fullSet.aliases?.[resolved]?.parent && depth < 10) {
          resolved = fullSet.aliases[resolved].parent;
          depth++;
        }
        if (fullSet.icons[resolved]) {
          subset.icons[name] = fullSet.icons[resolved];
          count++;
        } else {
          console.warn(`  ⚠ Icon "${prefix}:${name}" not found in set`);
        }
      }
    }

    collections.push(subset);
    console.log(`  ✓ ${prefix}: ${count} icons`);
  }

  return collections;
}

// ── main ──
console.log('🔍 Scanning icons...');
const found = scanIcons(SRC);

if (found.size === 0) {
  console.log('  No icons found in templates.');
  writeFileSync(OUT_FILE, '// No icons found — empty subset\nexport const iconSubset = [];\n', 'utf8');
  process.exit(0);
}

for (const [prefix, names] of found) {
  console.log(`  ${prefix}: ${names.size} references`);
}

console.log('\n📦 Building subset...');
const collections = buildSubset(found);

const outDir = dirname(OUT_FILE);
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

writeFileSync(
  OUT_FILE,
  `// Auto-generated by collect-icons.mjs — do not edit manually
import type { IconifyJSON } from '@iconify/types';

export const iconSubset: IconifyJSON[] = ${JSON.stringify(collections, null, 2)};
`,
  'utf8',
);

console.log(`\n✅ Subset written to ${OUT_FILE}`);
